### ISSUE TITLE
Issue tracker for Tutorial 04

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3940]
* [ ] The polymer simulation with Langevin Dynamics becomes extremely slow when the box size is increased from 12 to to 120.
* [ ] Look into simulating polymers in poor solvent by adding a LJ-cosine interaction: Lyulin et al. 1999 (doi:[10.1021/ma981818w](https://doi.org/10.1021/ma981818w)).
* [ ] The Flory theory is only valid for long polymers, look into corrections for finite chains. See e.g. Dünweg et al. 2002 (doi:[10.1063/1.1483296](https://doi.org/10.1063/1.1483296)) or Li et al. 1995 (doi:[10.1007/BF02178552](https://doi.org/10.1007/BF02178552)).
* [x] When fitting an affine function to the linear regime of the MSD, weight data points from the MSD correlator by the sample size of the bins to reduce the importance of the long time tail. This improves the agreement between the estimated diffusion coefficient and the Kirkwood-Zimm model.
* [x] In part 3, the Rouse model has a prefactor D0 (diffusion constant of the monomer), which has an analytical solution calculated in part 2. This can be used to check in CI the correctness of the first coefficient obtained from the fit.
* [x] In part 3, the Langevin Dynamics version can run with more polymer sizes and more time steps.

**Comment by fweik** [comment]
I'm not sure that introducing Green-Kubo and MSD for the diffusion at once is a good idea. It's too much at once, and a source of confusion, also it did not become clear when you would use what, for the given parameter sets they both work equally well.
I think that would still be the case if the polymer part would be factored out as proposed in #3939.

**Comment by jngrad** [comment]
Regarding performance for large box sizes: `boost::iterators::detail::iterator_facade_base<ParticleIterator<Cell**>>` accounts for 70% of the total runtime according to valgrind. It's called when iterating over `ParticleRanges` or `local_cells`. Increasing the skin by a factor 10 (the same factor as the box size) reduces the iterator footprint to 50% of the total runtime.

With the small box size, the iterator only accounts for 2% of the total runtime.
