### ISSUE TITLE
Issue tracker for Tutorial 11

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3942]
* [x] the HTML versions fail to run due to errors in lowercase/uppercase variable names
* [x] symbols in formula are not always consistent with symbols in the text (e.g. `\varphi` instead of `\phi`)
* [x] the formulation "we commit H.mu as the external magnetic field" is used in the sense of "we apply H.mu as...", and "we commit the orientation of the dipole moments" in the sense of "we set the orientation..."
* [ ] in part 3, check if it would be possible to calculate error bars for the plots

**Comment by RudolfWeeber** [comment]
Minor fixes will be provided by @pkreissl, error bars are deferred
