### ISSUE TITLE
Long-range actors should be script interface objects

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#4454]
Many electrostatic and magnetostatic methods implemented for the GPU have the following design:

```cython
IF ELECTROSTATICS and MMM1D_GPU:
    cdef class MMM1DGPU(ElectrostaticInteraction):
        cdef shared_ptr[Mmm1dgpuForce] sip
        cdef EspressoSystemInterface * interface

        def __cinit__(self):
            self.interface = &EspressoSystemInterface.Instance()
            self.sip = make_shared[Mmm1dgpuForce](dereference(self.interface))

        def _deactivate_method(self):
            dereference(self.sip).deactivate()
```

The `ScriptInterface` framework provides a convenient interface to store a shared pointer to a core class. It has many advantages:
* no need to manage a shared pointer, this is done by the script interface
* no need to store a raw pointer to the `EspressoSystemInterface` global variable
* no need to re-declare (and maintain) the core class in the .pxd file
* the Cython class can be converted to a regular Python class

The CPU implementations can also benefit from such a refactoring:
* no need to duplicate class declarations in the .pxd files
* all electrostatics and magnetostatics core global variables can be removed

## Roadmap

**Rewrite electrostatic and magnetostatic methods as C++ classes**
* [x] improve interface segregation and encapsulate algorithms in classes
* [x] do dependency inversion (e.g. `dipoles.hpp` should include all magnetostatic methods, instead of all magnetostatic methods including `dipoles.hpp`)
* [x] extract common code (P3M data structs and utility functions, FFT code)
* [x] move actor source files to the electrostatics or magnetostatics modules
* [x] remove the `Actors` framework in the core
* [x] split electrostatic methods from magnetostatic methods
   * the core should have three new folders: `electrostatics`, `magnetostatics`, `p3m` (for common P3M code and FFT)
   * the core should no longer have folders `actors`, `electrostatics_magnetostatics`
* [x] split ScaFaCoS electrostatic methods from ScaFaCoS magnetostatic methods

**Write the script interface**
* [x] write `ScriptInterface` classes for electrostatic methods
* [x] write `ScriptInterface` classes for magnetostatic methods
* [x] write `ScriptInterface` classes for ScaFaCoS methods
* [x] sort out issues related to MPI errors when throwing exceptions on worker nodes, e.g. in the constructors and tuning functions (see #4449)
* [x] sort out issues related to MPI deadlock when mixing `boost::mpi` communication with `MpiCallbacks` communication

**Roll out changes to the core**
* [x] remove all electrostatics/magnetostatics global variables in the core
* [x] add `boost::optional<boost::variant<Method1,Method2,Method3>> magnetostatics_actor` global variables in the core
* [x] implement boost visitors for the energy, force and pressure calculation
* [x] make DLC a stand alone actor instead of an extension to break dependencies in the core and lift ambiguities in the script interface (see #2155)
   * e.g. what should be the state of `DipolarP3M` when removing the `DLC` "extension"? The `DipolarP3M` force and energy kernels are not `const`, therefore the actor will be altered and no longer be in sync with the `DP3M` python class. Making the `DP3M` actor an argument of `DLC` removes the ambiguity. In addition, the Cython `Actors` class no longer has to keep track of active actors vs. active extensions.
* [x] clarify when `on_coulomb_change()`, parameter broadcasts and long-range actor sanity checks are really needed; right now they are called in too many places (e.g. sanity checks are run at each integration step during tuning) and parameter broadcasts override each other when an actor is adapted by `ELC` or `DLC`. Parameter broadcasts need to be removed entirely by making the tuning code synchronous, sanity checks should only be executed when an actor is active, and the `on_coulomb_change()` should only be called when activating, deactivating or modifying the state of an actor.
* [x] runtime errors triggered by long-range actor sanity checks are queued and their handling is sometimes deferred to the integration loop, which is too late (fixed by #4479)
* [x] break dependencies in the core: at the moment, `coulomb.hpp` is indirectly included in around 60 files, half of which are totally unrelated to electrostatics; to break this chain of includes, we need to make the `BondedCoulombSR` kernels non-inline (i.e. remove its `#include "coulomb_inline.hpp"` and move it to a .cpp file) and split the pair criteria into individual classes
* [x] decouple magnetostatics events from electrostatics events (for example, modifying the `DipolarP3M` parameters should not reinitialize the `P3MGPU` parameters)
