### ISSUE TITLE
Walberla performance tracking ticket

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#4989]
* [x] more selective ghost communication #4921 
* [x] Use AVX vectorization in all kernels (streaming, boundaries, reset force, ...). (It might be useful to automate the generatoin of kernel_traits.hpp, first (#4988)
* [ ] replace 
* [x] switch to pull scheme and use combined stream-collide sweep (postponed, as I couldn't get our patched bounce back boundary condiont working with pull scheme)
* [x] Generate the packinfos using PyStencils and use vectorization (currently, we use hand-written pack infos form Walberla propper). In particular, do such generated packinfos outperform the currenty used memcpy pack info on the GPU
* [x] Multi-GPu simulatoin with cCuda-aware MPI

**Comment by RudolfWeeber** [comment]
Just realized that we did not yet vectorize the streaming kernel. This is probably a relatively low hanging fruit for performance on CPU.
