### ISSUE TITLE
P3M + Heffte tracking ticket

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#5010]
The prototype is in my Github in the branch heffte

* [X] Basic implementation of Hefte-based 3d FFt in electrostatic P3M
* [x] Get rid of segfaults for 2 core parallel simulationsand for non-cubic simulation box (primary suspect are NaN in influence functions)
* [x] Do a more detailed performance analysis of the K-space kernel.
    * [x] figure out if all std::complex slowness is avoided, or if we need a different complex implementation
    * [x] annotate different regoins and functions with Caliper and measure performance vs number of cores
        * charge assignment
        * halo communication for real space charge density
        * halo removal
        * 3d FFT
        * k-space force calc
        * Backward 3d fft
        * Introduciotn of space for halos
        * halo comm of E real-space fields
        * force assignment
* [ ] instance the Heffte fft3d with a sub-communicaotr, such that the reshaping is done on a single core
* [x] enable OpenMP for heffte
* [x] clean-up Heffte CMake integration

GPU and electrostatic pressure can probably wait until we have the CPU forces right.
